### ISSUE TITLE
[BUG] Image DataFrame does not seem to be properly constructed

### ISSUE THREAD

**Issue by sgibson91** [HelmUpgradeBot/DockerCleanUp#26]
First error:

```
Traceback (most recent call last):
  File "/Users/sgibson/anaconda3/envs/DockerCleanUp/bin/DockerCleanUpBot", line 11, in <module>
    load_entry_point('DockerCleanUpBot==0.0.1', 'console_scripts', 'DockerCleanUpBot')()
  File "/Users/sgibson/anaconda3/envs/DockerCleanUp/lib/python3.7/site-packages/DockerCleanUpBot-0.0.1-py3.7.egg/DockerCleanUpBot/cli.py", line 46, in main
  File "/Users/sgibson/anaconda3/envs/DockerCleanUp/lib/python3.7/site-packages/DockerCleanUpBot-0.0.1-py3.7.egg/DockerCleanUpBot/DockerCleanUpBot.py", line 39, in clean_up
  File "/Users/sgibson/anaconda3/envs/DockerCleanUp/lib/python3.7/site-packages/DockerCleanUpBot-0.0.1-py3.7.egg/DockerCleanUpBot/DockerCleanUpBot.py", line 314, in sort_and_delete
AttributeError: 'NoneType' object has no attribute 'loc'
```

Think this springs from the `delete_ci_images` function - which probably should be behind a flag anyway as not all hubs have ci built images

**Comment by sgibson91** [comment]
Second error (raised with `delete_ci_images` function commented out):

```
Traceback (most recent call last):
  File "/Users/sgibson/anaconda3/envs/DockerCleanUp/bin/DockerCleanUpBot", line 11, in <module>
    load_entry_point('DockerCleanUpBot==0.0.1', 'console_scripts', 'DockerCleanUpBot')()
  File "/Users/sgibson/anaconda3/envs/DockerCleanUp/lib/python3.7/site-packages/DockerCleanUpBot-0.0.1-py3.7.egg/DockerCleanUpBot/cli.py", line 46, in main
  File "/Users/sgibson/anaconda3/envs/DockerCleanUp/lib/python3.7/site-packages/DockerCleanUpBot-0.0.1-py3.7.egg/DockerCleanUpBot/DockerCleanUpBot.py", line 39, in clean_up
  File "/Users/sgibson/anaconda3/envs/DockerCleanUp/lib/python3.7/site-packages/DockerCleanUpBot-0.0.1-py3.7.egg/DockerCleanUpBot/DockerCleanUpBot.py", line 347, in sort_and_delete
  File "/Users/sgibson/anaconda3/envs/DockerCleanUp/lib/python3.7/site-packages/pandas/core/frame.py", line 4097, in drop
    errors=errors,
  File "/Users/sgibson/anaconda3/envs/DockerCleanUp/lib/python3.7/site-packages/pandas/core/generic.py", line 3915, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/Users/sgibson/anaconda3/envs/DockerCleanUp/lib/python3.7/site-packages/pandas/core/generic.py", line 3947, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/sgibson/anaconda3/envs/DockerCleanUp/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 5333, in drop
    raise KeyError("{} not found in axis".format(labels[mask]))
KeyError: "['hub23/binder-dev-sgibson91-2dmagprop-cfee96@sha256:7f05804d2878bf88f838bd3053f072c796707d12d24c81ff059bedee9a74b9fc'] not found in axis"
```
